set(kiwi_data ../../iOS/Kiwi/Kiwi/Data)

set(brain_atlas_dir ${kiwi_data}/brain_atlas)
set(can_dir ${kiwi_data}/can)

set(assets
  ${kiwi_data}/AppendedKneeData.vtp
  ${kiwi_data}/Buckyball.vtp
  ${kiwi_data}/MountStHelen.vtp
  ${kiwi_data}/bunny.vtp
  ${kiwi_data}/caffeine.pdb
  ${kiwi_data}/shuttle.vtp
  ${kiwi_data}/teapot.vtp
  ${kiwi_data}/visible-woman-hand.vtp
  ${kiwi_data}/head.vti
  ${kiwi_data}/kiwi.png
  ${kiwi_data}/cturtle.vtp
  ${kiwi_data}/textured_sphere.vtp
  ${kiwi_data}/earth.jpg


  ${brain_atlas_dir}/Skin.vtp
  ${brain_atlas_dir}/VPL_thalamic_nucleus_L.vtp
  ${brain_atlas_dir}/VPL_thalamic_nucleus_R.vtp
  ${brain_atlas_dir}/VPM_thalamic_nucleus_L.vtp
  ${brain_atlas_dir}/VPM_thalamic_nucleus_R.vtp
  ${brain_atlas_dir}/abducent_nerve_L.vtp
  ${brain_atlas_dir}/abducent_nerve_R.vtp
  ${brain_atlas_dir}/accessory_nerve_L.vtp
  ${brain_atlas_dir}/accessory_nerve_R.vtp
  ${brain_atlas_dir}/amygdaloid_body_L.vtp
  ${brain_atlas_dir}/amygdaloid_body_R.vtp
  ${brain_atlas_dir}/angular_gyrus_inferior_parietal_lobule_L.vtp
  ${brain_atlas_dir}/angular_gyrus_inferior_parietal_lobule_R.vtp
  ${brain_atlas_dir}/anterior_commissure.vtp
  ${brain_atlas_dir}/anterior_substantia_perforata_L.vtp
  ${brain_atlas_dir}/anterior_substantia_perforata_R.vtp
  ${brain_atlas_dir}/anterior_thalamic_nucleus_L.vtp
  ${brain_atlas_dir}/anterior_thalamic_nucleus_R.vtp
  ${brain_atlas_dir}/atlas.vtp
  ${brain_atlas_dir}/axis.vtp
  ${brain_atlas_dir}/caudate_nucleus_L.vtp
  ${brain_atlas_dir}/caudate_nucleus_R.vtp
  ${brain_atlas_dir}/centromedian_thalamic_nucleus_L.vtp
  ${brain_atlas_dir}/centromedian_thalamic_nucleus_R.vtp
  ${brain_atlas_dir}/cerebellar_hemisphere_L.vtp
  ${brain_atlas_dir}/cerebellar_hemisphere_R.vtp
  ${brain_atlas_dir}/cerebellar_tonsil_L.vtp
  ${brain_atlas_dir}/cerebellar_tonsil_R.vtp
  ${brain_atlas_dir}/cerebellar_vermis.vtp
  ${brain_atlas_dir}/cerebellar_white_matter.vtp
  ${brain_atlas_dir}/cingulate_gyrus_L.vtp
  ${brain_atlas_dir}/cingulate_gyrus_R.vtp
  ${brain_atlas_dir}/corpus_callosum.vtp
  ${brain_atlas_dir}/corticospinal_tract_L.vtp
  ${brain_atlas_dir}/corticospinal_tract_R.vtp
  ${brain_atlas_dir}/dentate_nucleus_L.vtp
  ${brain_atlas_dir}/dentate_nucleus_R.vtp
  ${brain_atlas_dir}/dorsomedial_thalamic_nucleus_L.vtp
  ${brain_atlas_dir}/dorsomedial_thalamic_nucleus_R.vtp
  ${brain_atlas_dir}/external_capsule_L.vtp
  ${brain_atlas_dir}/external_capsule_R.vtp
  ${brain_atlas_dir}/eyeball_L.vtp
  ${brain_atlas_dir}/eyeball_R.vtp
  ${brain_atlas_dir}/facial_nerve_L.vtp
  ${brain_atlas_dir}/facial_nerve_R.vtp
  ${brain_atlas_dir}/fornix.vtp
  ${brain_atlas_dir}/fourth_ventricle_aqueduct.vtp
  ${brain_atlas_dir}/globus_pallidus_L.vtp
  ${brain_atlas_dir}/globus_pallidus_R.vtp
  ${brain_atlas_dir}/glossopharyngeal_nerve_L.vtp
  ${brain_atlas_dir}/glossopharyngeal_nerve_R.vtp
  ${brain_atlas_dir}/hemispheric_white_matter.vtp
  ${brain_atlas_dir}/hippocampus_L.vtp
  ${brain_atlas_dir}/hippocampus_R.vtp
  ${brain_atlas_dir}/hypoglossal_nerve_L.vtp
  ${brain_atlas_dir}/hypoglossal_nerve_R.vtp
  ${brain_atlas_dir}/hypothalamus.vtp
  ${brain_atlas_dir}/inferior_cerebellar_peduncle_L.vtp
  ${brain_atlas_dir}/inferior_cerebellar_peduncle_R.vtp
  ${brain_atlas_dir}/inferior_colliculus_L.vtp
  ${brain_atlas_dir}/inferior_colliculus_R.vtp
  ${brain_atlas_dir}/inferior_frontal_gyrus_L.vtp
  ${brain_atlas_dir}/inferior_frontal_gyrus_R.vtp
  ${brain_atlas_dir}/inferior_temporal_gyrus_L.vtp
  ${brain_atlas_dir}/inferior_temporal_gyrus_R.vtp
  ${brain_atlas_dir}/insula_L.vtp
  ${brain_atlas_dir}/insula_R.vtp
  ${brain_atlas_dir}/internal_capsule_L.vtp
  ${brain_atlas_dir}/internal_capsule_R.vtp
  ${brain_atlas_dir}/internal_capsule_post_L.vtp
  ${brain_atlas_dir}/internal_capsule_post_R.vtp
  ${brain_atlas_dir}/internal_medullar_lamina_L.vtp
  ${brain_atlas_dir}/internal_medullar_lamina_R.vtp
  ${brain_atlas_dir}/lateral_dorsal_thalamic_nucleus_L.vtp
  ${brain_atlas_dir}/lateral_dorsal_thalamic_nucleus_R.vtp
  ${brain_atlas_dir}/lateral_geniculate_body_L.vtp
  ${brain_atlas_dir}/lateral_geniculate_body_R.vtp
  ${brain_atlas_dir}/lateral_occipitotemporal_gyrus_L.vtp
  ${brain_atlas_dir}/lateral_occipitotemporal_gyrus_R.vtp
  ${brain_atlas_dir}/lateral_posterior_thalamic_nucleus_L.vtp
  ${brain_atlas_dir}/lateral_posterior_thalamic_nucleus_R.vtp
  ${brain_atlas_dir}/lateral_ventricle_L.vtp
  ${brain_atlas_dir}/lateral_ventricle_R.vtp
  ${brain_atlas_dir}/mamillary_body_L.vtp
  ${brain_atlas_dir}/mamillary_body_R.vtp
  ${brain_atlas_dir}/medial_geniculate_body_L.vtp
  ${brain_atlas_dir}/medial_geniculate_body_R.vtp
  ${brain_atlas_dir}/medial_occipitotemporal_parahippocampal_gyrus_L.vtp
  ${brain_atlas_dir}/medial_occipitotemporal_parahippocampal_gyrus_R.vtp
  ${brain_atlas_dir}/medulla_oblongata.vtp
  ${brain_atlas_dir}/midbrain.vtp
  ${brain_atlas_dir}/middle_cerebellar_peduncle_L.vtp
  ${brain_atlas_dir}/middle_cerebellar_peduncle_R.vtp
  ${brain_atlas_dir}/middle_frontal_gyrus_L.vtp
  ${brain_atlas_dir}/middle_frontal_gyrus_R.vtp
  ${brain_atlas_dir}/middle_temporal_gyrus_L.vtp
  ${brain_atlas_dir}/middle_temporal_gyrus_R.vtp
  ${brain_atlas_dir}/model_info.txt
  ${brain_atlas_dir}/nucleus_accumbens_L.vtp
  ${brain_atlas_dir}/nucleus_accumbens_R.vtp
  ${brain_atlas_dir}/nucleus_habenulae_L.vtp
  ${brain_atlas_dir}/nucleus_habenulae_R.vtp
  ${brain_atlas_dir}/occipital_lobe_L.vtp
  ${brain_atlas_dir}/occipital_lobe_R.vtp
  ${brain_atlas_dir}/occulomotor_nerve_L.vtp
  ${brain_atlas_dir}/occulomotor_nerve_R.vtp
  ${brain_atlas_dir}/optic_chiasm.vtp
  ${brain_atlas_dir}/optic_nerve_L.vtp
  ${brain_atlas_dir}/optic_nerve_R.vtp
  ${brain_atlas_dir}/optic_radiation_L.vtp
  ${brain_atlas_dir}/optic_radiation_R.vtp
  ${brain_atlas_dir}/optic_tract_L.vtp
  ${brain_atlas_dir}/optic_tract_R.vtp
  ${brain_atlas_dir}/orbital_gyri_gyrus_rectus_L.vtp
  ${brain_atlas_dir}/orbital_gyri_gyrus_rectus_R.vtp
  ${brain_atlas_dir}/pellucid_septum.vtp
  ${brain_atlas_dir}/pineal_body.vtp
  ${brain_atlas_dir}/pituitary_gland.vtp
  ${brain_atlas_dir}/pons.vtp
  ${brain_atlas_dir}/postcentral_gyrus_L.vtp
  ${brain_atlas_dir}/postcentral_gyrus_R.vtp
  ${brain_atlas_dir}/posterior_commissure.vtp
  ${brain_atlas_dir}/posterior_substantia_perforata.vtp
  ${brain_atlas_dir}/precentral_gyrus_L.vtp
  ${brain_atlas_dir}/precentral_gyrus_R.vtp
  ${brain_atlas_dir}/pulvinar_L.vtp
  ${brain_atlas_dir}/pulvinar_R.vtp
  ${brain_atlas_dir}/putamen_L.vtp
  ${brain_atlas_dir}/putamen_R.vtp
  ${brain_atlas_dir}/red_nucleus_L.vtp
  ${brain_atlas_dir}/red_nucleus_R.vtp
  ${brain_atlas_dir}/septal_nucleus_L.vtp
  ${brain_atlas_dir}/septal_nucleus_R.vtp
  ${brain_atlas_dir}/skull_bone.vtp
  ${brain_atlas_dir}/substantia_nigra_L.vtp
  ${brain_atlas_dir}/substantia_nigra_R.vtp
  ${brain_atlas_dir}/superior_cerebellar_peduncle_L.vtp
  ${brain_atlas_dir}/superior_cerebellar_peduncle_R.vtp
  ${brain_atlas_dir}/superior_colliculus_L.vtp
  ${brain_atlas_dir}/superior_colliculus_R.vtp
  ${brain_atlas_dir}/superior_frontal_gyrus_L.vtp
  ${brain_atlas_dir}/superior_frontal_gyrus_R.vtp
  ${brain_atlas_dir}/superior_medullar_velum.vtp
  ${brain_atlas_dir}/superior_parietal_lobule_L.vtp
  ${brain_atlas_dir}/superior_parietal_lobule_R.vtp
  ${brain_atlas_dir}/superior_temporal_gyrus_ant_L.vtp
  ${brain_atlas_dir}/superior_temporal_gyrus_ant_R.vtp
  ${brain_atlas_dir}/superior_temporal_gyrus_post_L.vtp
  ${brain_atlas_dir}/superior_temporal_gyrus_post_R.vtp
  ${brain_atlas_dir}/supramarginal_gyrus_inferior_parietal_lobule_L.vtp
  ${brain_atlas_dir}/supramarginal_gyrus_inferior_parietal_lobule_R.vtp
  ${brain_atlas_dir}/temporal_pole_L.vtp
  ${brain_atlas_dir}/temporal_pole_R.vtp
  ${brain_atlas_dir}/third_ventricle.vtp
  ${brain_atlas_dir}/trigeminal_nerve_L.vtp
  ${brain_atlas_dir}/trigeminal_nerve_R.vtp
  ${brain_atlas_dir}/trochlearis_nerve_L.vtp
  ${brain_atlas_dir}/trochlearis_nerve_R.vtp
  ${brain_atlas_dir}/vagal_nerve_L.vtp
  ${brain_atlas_dir}/vagal_nerve_R.vtp
  ${brain_atlas_dir}/ventral_anterior_thalamic_nucleus_L.vtp
  ${brain_atlas_dir}/ventral_anterior_thalamic_nucleus_R.vtp
  ${brain_atlas_dir}/ventral_lateral_thalamic_nucleus_L.vtp
  ${brain_atlas_dir}/ventral_lateral_thalamic_nucleus_R.vtp
  ${brain_atlas_dir}/vestibulocochlear_nerve_L.vtp
  ${brain_atlas_dir}/vestibulocochlear_nerve_R.vtp

  ${can_dir}/can0000.vtp
  ${can_dir}/can0001.vtp
  ${can_dir}/can0002.vtp
  ${can_dir}/can0003.vtp
  ${can_dir}/can0004.vtp
  ${can_dir}/can0005.vtp
  ${can_dir}/can0006.vtp
  ${can_dir}/can0007.vtp
  ${can_dir}/can0008.vtp
  ${can_dir}/can0009.vtp
  ${can_dir}/can0010.vtp
  ${can_dir}/can0011.vtp
  ${can_dir}/can0012.vtp
  ${can_dir}/can0013.vtp
  ${can_dir}/can0014.vtp
  ${can_dir}/can0015.vtp
  ${can_dir}/can0016.vtp
  ${can_dir}/can0017.vtp
  ${can_dir}/can0018.vtp
  ${can_dir}/can0019.vtp
  ${can_dir}/can0020.vtp
  ${can_dir}/can0021.vtp
  ${can_dir}/can0022.vtp
  ${can_dir}/can0023.vtp
  ${can_dir}/can0024.vtp
  ${can_dir}/can0025.vtp
  ${can_dir}/can0026.vtp
  ${can_dir}/can0027.vtp
  ${can_dir}/can0028.vtp
  ${can_dir}/can0029.vtp
  ${can_dir}/can0030.vtp
  ${can_dir}/can0031.vtp
  ${can_dir}/can0032.vtp
  ${can_dir}/can0033.vtp
  ${can_dir}/can0034.vtp
  ${can_dir}/can0035.vtp
  ${can_dir}/can0036.vtp
  ${can_dir}/can0037.vtp
  ${can_dir}/can0038.vtp
  ${can_dir}/can0039.vtp
  ${can_dir}/can0040.vtp
  ${can_dir}/can0041.vtp
  ${can_dir}/can0042.vtp
  ${can_dir}/can0043.vtp
  )

foreach(f ${assets})
  get_filename_component(fname ${f} NAME)
  configure_file(${f} ${CMAKE_BINARY_DIR}/assets/${fname} COPYONLY)
endforeach()
